version: '3.8'
x-app_common: &app_common
  build:
    context: ../..
    dockerfile: ops/dev/Dockerfile
  tmpfs:
    - /tmp

x-backend: &backend
  <<: *app_common
  stdin_open: true
  tty: true
  volumes:
    - ../..:/app/:cached
    - node_modules:/app/node_modules
  env_file:
    - app_env
    - app_env.secrets
  environment:
    - WEB_CONCURRENCY=1
    - EDITOR=vi
  depends_on:
    - postgres
    - redis

services:
  app:
    <<: *backend
    command: bin/rails server -b 0.0.0.0
    ports:
      - '3000:3000'

  jobs:
    <<: *backend
    command: bundle exec sidekiq -C config/sidekiq.yml

  postgres:
    image: postgres:12.3
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./log:/root/log:cached
    environment:
      - POSTGRES_DB=bosa_dev
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s

  redis:
    image: redis:6.0-alpine
    volumes:
      - redis:/data
    ports:
      - 6379
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  postgres:
  redis:
  bundle:
  node_modules:
